version: '3.8'

services:
  web:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
      - staticfiles:/app/staticfiles
    env_file:
      - .env
    depends_on:
      - db
    command: >
      sh -c "python manage.py migrate &&
            python manage.py createsuperuser &&
             python manage.py runserver 0.0.0.0:8000"

  db:
    image: postgres:14
    ports:
      - "5432:5432"
    env_file:
      - .env
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  static_volume:
  media_volume:
  staticfiles:
  pgdata: